name: online_course
description: Online Course App.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  cloudinary_flutter: ^1.3.0  # Phiên bản mới nhất
  cloudinary_url_gen: ^1.8.0  # Phiên bản mới nhất
  flutter_bloc: ^9.1.1
  flutter_custom_tab_bar: ^1.2.1
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.2.2
  get_it: ^8.2.0
  http: ^1.1.0
  mocktail: ^1.0.0
  readmore: ^3.0.0
  chewie: ^1.13.0
  video_player: ^2.10.0


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/categories/
